### ISSUE TITLE
Incorporate different types of meta-learners

### ISSUE THREAD

**Issue by jialul** [MichaelLLi/evalITR#24]
Create an option of X-learner, T-learner, and R-learner for lasso and BART and allow user to choose different meta-learner types.

**Comment by xiaolong-y** [comment]
To do so we can look into the following two packages:
- X-learner ([`causalToolbox`](https://github.com/forestry-labs/causalToolbox))
- R-learner ([`rlearner`](https://github.com/xnie/rlearner/) which also implements S-, T-, U-, and X-learners)

`rlearner` might be a good place to start with since it is an encapsulating package. 

Afterwhich, we can also expand our support causality specific packages like `doubleML`. Some of listed [here](https://github.com/MichaelLLi/evalITR/pull/5#issuecomment-1225898059).

**Comment by jialul** [comment]
Added R-T-X-U learner in commit `[571bb2e](https://github.com/MichaelLLi/evalITR/commit/571bb2e7bba2d2a15e742f4e735339ca88cfa2ae)`
